shinage_management:
  prefix: "manage"
  resource: "routes/routing_manage.yml"

shinage_presentations:
  prefix: "presentations"
  resource: "routes/routing_presentations.yml"

shinage_api_v1:
  prefix: "/api/v1"
  resource: "routes/api_v1.yml"

_screen_remote_api:
  prefix: "/screen-remote"
  resource: "routes/screen_remote.yml"


# Security
shinage_register:
  prefix: "/register"
  resource: "routes/register.yml"

app_manage_login:
  path: "/login"
  controller: App\Controller\Security\LoginController::loginAction

app_manage_logout:
  path: "/logout"
  controller: App\Controller\Security\LoginController::logoutAction

app_manage_login_check:
  path: "/login-check"
  controller: App\Controller\Security\LoginController::checkAction

# @TODO Reset Password

homepage:
  path: "/"
  controller: App\Controller\DefaultController::indexAction

pool-get:
  path: /pool/{userRoot}/{path}
  controller: App\Controller\PoolController::getAction
  requirements:
    userRoot: "[^/]*"
    path: ".*"

pool-get-root:
  path: /pool/

qr-for-screen-registration:
  path: /qr/register-screen/{connectCode}
  controller: App\Controller\QrController::registerScreenUrlAction
  requirements:
    connectCode: .+
